language: ruby
# if the ruby version is not specified by the rvm key
# Travis CI uses the .ruby-version file in the root of the repository
env:
  global:
  - TRAVIS_NODE_VERSION="v12.19.0"
  - GH_REF=github.com/IFRCGo/global-services.git
  - DEPLOY_BRANCH=publish
  matrix:
    secure: QbglDx+eWrJ1/15wAzSaVZW+yXTdETxBEwAPrVYSPmO/emzwaB4/L802nCnVCIK6dF++cQGeLHL73T007myAgwuX6vJS8X6td/XfD6gI5/2jZKhut3yx3YdzuIqgZ1y246aALg/trrF3b/WdjnMCAETI79WYwKl0omipXoxrbur3JY+WJCUYF/DuNJQP3hXN5o89eaBUqeZgiPAPEb2XWVwVJ+97vu20axPw7ygl7x76J23Bv4d7Sggq3VsrxhtS/Akw8/0p+sBZudXhHSo9U+MUCdWRnvpVU/ncF+4X2EBsNFPYn7j4iMwN5oiP6q3vnH4mujSud3LHrRitPzWYKoQod9Wza4zqOvtvpGPlCDkavDtW0QolbD0gB0tI+yfpcptTYkr3MIquVyoB7HtVg+Skm/0aA/4p6egYStDFxoJKz5Jr2F9pYq4DqhK9WuQ/Sz3oa8CxHZZIHivpSzEc8QEely/mhygQw/HkQHv1R1h9OSxLJPrzLqIhOTCWlt4+8irp6zGItYgmynVYRpwlBIlZGVIoGxiG8y73UVRSFKuZnn59mfWwLe6Tr5I2C7peuc5QkfHWi0vGduXxNjgOoYDsM5waOtBzZTXiIHLnDl+kCljL/vfe6vcUd7cUZdb7J0R+d9owOQVwIjGAzwSur64HrJ/r6SjXe02ctakXkCs=
before_script:
- ". $HOME/.nvm/nvm.sh"
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- npm install -g gulp
- npm install
script: gulp prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: false
  on:
    branch: publish
  local_dir: _site
