source:       app
baseurl:      "https://ifrcgo.github.io/global-services" 

markdown:   kramdown
permalink:  pretty
exclude:
  - assets/styles
  - README.md
  - font-generator
  
default_locale:     "en"
authorized_locales: ["en", "es"]
locale_names:
  en: "English"
  es: "Español"

collections_dir: services
collections:
  assessment:
    output: true
    en: 
      url: "/assessment/"
    es: 
      url: "/es/assessment/"
  cea:
    output: true
    en: 
      url: "/cea/"
    es: 
      url: "/es/cea/"
  health:
    output: true
    en: 
      url: "/health/"
    es: 
      url: "/es/salud/"
  logs:
    output: true
    en: 
      url: "/logistics/"
    es: 
      url: "/es/logistica/"
  wash:
    output: true
    en: 
      url: "/wash/"
    es: 
      url: "/es/wash/"  

        